// Usage: npm run weekly-review
// Reads the 7-day window from CSVs and produces an AI-generated markdown report.
import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';
import { callOpenRouter } from '../lib/openrouter';

const DATA_DIR = path.resolve(__dirname, '../data');
const REPORTS_DIR = path.resolve(__dirname, '../reports');

function readCsv(name: string): string {
  const p = path.join(DATA_DIR, name);
  if (!fs.existsSync(p)) return `(no ${name} yet)`;
  return fs.readFileSync(p, 'utf-8').trim();
}

function last7Days(csv: string): string {
  const lines = csv.split('\n').filter(Boolean);
  if (lines.length <= 1) return csv;
  const header = lines[0];
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - 7);

  // Find the date column index: look for *_at columns (applied_at, skipped_at, etc.)
  const cols = header.split(',');
  const dateCol = cols.findIndex((c) => c.endsWith('_at') || c === 'started_at' || c === 'ended_at');

  const filtered = lines.slice(1).filter((line) => {
    if (dateCol < 0) return true;
    const parts = line.split(',');
    const dateStr = parts[dateCol]?.replace(/"/g, '');
    if (!dateStr) return true;
    return new Date(dateStr) >= cutoff;
  });

  return [header, ...filtered].join('\n');
}

async function main() {
  const applications = last7Days(readCsv('applications.csv'));
  const skipped = last7Days(readCsv('skipped_jobs.csv'));
  const failed = last7Days(readCsv('failed_jobs.csv'));
  const runs = last7Days(readCsv('runs.csv'));

  const appLines = applications.split('\n').filter(Boolean).length - 1;
  const skipLines = skipped.split('\n').filter(Boolean).length - 1;
  const failLines = failed.split('\n').filter(Boolean).length - 1;

  console.log(`Generating weekly review — ${appLines} apps, ${skipLines} skips, ${failLines} failures in last 7 days`);

  const prompt = `You are reviewing a week of automated job application bot activity for a candidate named Rumman Riyaz.

Candidate profile:
- Roles: Project Manager (ICT), Technical PM, Delivery Lead, Software Engineer, Full Stack, Backend, Cloud/AI Engineer
- Target salary: $120,000–$150,000 AUD
- Location: Newcastle/Sydney/Brisbane, hybrid or remote preferred

Data from the last 7 days:

=== RUNS ===
${runs}

=== APPLICATIONS (jobs successfully applied to) ===
${applications}

=== SKIPPED JOBS ===
${skipped}

=== FAILED JOBS (bot could not complete) ===
${failed}

Write a concise weekly review in markdown with these sections:
1. **Summary** — total applied/skipped/failed counts, how many runs, dates covered
2. **Top skip reasons** — which skip reasons appeared most and what they mean
3. **Top failure reasons** — which failure reasons appeared most (if any)
4. **Notable applications** — stand-out companies or roles applied to (if any)
5. **Suggested improvements** — 2–4 specific changes to improve the bot's success rate based on the data above

Keep it practical and under 400 words. Format the date range clearly.`;

  let report: string;
  try {
    report = await callOpenRouter(prompt);
  } catch (err) {
    console.error('OpenRouter call failed:', err);
    process.exit(1);
  }

  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  const dateStr = new Date().toISOString().slice(0, 10);
  const outPath = path.join(REPORTS_DIR, `weekly-review-${dateStr}.md`);
  const full = `# Weekly Review — ${dateStr}\n\n_Generated by seek-automation bot_\n\n${report}\n\n---\n\n## Raw counts (last 7 days)\n\n- Applied: ${appLines}\n- Skipped: ${skipLines}\n- Failed: ${failLines}\n`;
  fs.writeFileSync(outPath, full, 'utf-8');
  console.log(`Report written to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
